// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92aNQkuzEYp8x11O-yRP8QxB-CX2-Cms',
    appId: '1:434674277031:web:191832329cccda8ae61982',
    messagingSenderId: '434674277031',
    projectId: 'translator-project-13be4',
    authDomain: 'translator-project-13be4.firebaseapp.com',
    storageBucket: 'translator-project-13be4.appspot.com',
    measurementId: 'G-E043J9X77L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJ-JGvm-aPvW9iDYmkW3cqm7y-xIasi0',
    appId: '1:434674277031:android:fac307e5a441d6c6e61982',
    messagingSenderId: '434674277031',
    projectId: 'translator-project-13be4',
    storageBucket: 'translator-project-13be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMFLNSHUJs6vMAN7y_H58-9m94fnL8K8',
    appId: '1:434674277031:ios:e5a375ac3932a29ce61982',
    messagingSenderId: '434674277031',
    projectId: 'translator-project-13be4',
    storageBucket: 'translator-project-13be4.appspot.com',
    iosBundleId: 'com.example.translatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMFLNSHUJs6vMAN7y_H58-9m94fnL8K8',
    appId: '1:434674277031:ios:ef3b96fedac39d6ce61982',
    messagingSenderId: '434674277031',
    projectId: 'translator-project-13be4',
    storageBucket: 'translator-project-13be4.appspot.com',
    iosBundleId: 'com.example.translatorApp.RunnerTests',
  );
}
